name: build
# When the 'permissions' key is specified, unspecified permission scopes (e.g.,
# actions, checks, etc.) are set to no access (none).
permissions:
  contents: read
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # Run daily (* is a special character in YAML, so quote the string)
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      # When git-ref is empty, HEAD will be checked out.
      git-ref:
        description: Optional git ref (branch, tag, or full SHA)
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # When the ref is empty, HEAD will be checked out.
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Dependencies
        run: npm install jsdom

      - name: Test
        run: node tests.js
